name: recycling_app
description: Recycling app using machine learning and flutter

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  image_picker: ^0.6.1+10
  torch_mobile: ^0.0.2

dev_dependencies:
  flutter_test:
   sdk: flutter

flutter:
  uses-material-design: true
  assets:
   - assets/



